Replace the Logo with Meshery in config.yml
meshery/meshery-linkerd pull request #492
Opened 2023-04-17 07:25 UTC by Simar-malhotra09

**Description**

 Replaced  the Layer5 logo with Meshery in the config.yml workflow file and to account for dark and light theme.

**Notes for Reviewers**
Please review the changes to ensure that the Meshery logo has been correctly added to the config.yml workflow file and that there are no unintended consequences of this change. Additionally, please let me know if there are any other places where the Layer5 logo needs to be updated to Meshery.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-05-12 22:31 UTC, leecalcote requested changes

2023-05-12 22:31 UTC, leecalcote commented on .github/config.yml
> +  <img alt="Shows a black logo in light color mode and a white one in dark color mode." src="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
Thanks, @Simar-malhotra09. This source needs to be changed. // @goldfishdolphin

2023-05-15 13:44 UTC, thisiskaransgit commented
@Simar-malhotra09, what's your progress, if you are stuck somewhere discuss it on slack, and also fix the merge conflicts

2023-05-15 14:25 UTC, Simar-malhotra09 commented
@thisiskaransgit hey, sorry for some reason i did not get the notification regarding the changes requested. I unforseably had to move countries, so i couldn't find the time to check in either. This change should be simple enough, i'll get to it asap

2023-05-15 14:52 UTC, thisiskaransgit requested changes

2023-05-15 14:52 UTC, thisiskaransgit commented on .github/config.yml
>    Thanks for your contribution to the Layer5 community! :tada:
```suggestion
  Thanks for your contribution to Meshery! :tada:
```
And, 
We recommend using uniform name conventions for images throughout the project, update the names to
Meshery-celebration-Dark.svg
Meshery-celebration-Light.svg

2023-05-15 15:07 UTC, goldfishdolphin reviewed
Please change the source of images to .github folder and update the path.

2023-05-15 15:07 UTC, goldfishdolphin commented on .github/config.yml
> +  <source media="(prefers-color-scheme: dark)" srcset="../img/meshery_dark.svg">
```suggestion
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/meshery/meshery-linked/master/.github/welcome/meshery_dark.svg">
```

2023-05-22 18:38 UTC, thisiskaransgit commented
@Simar-malhotra09, are you working on it, if not signal please signal

2023-06-09 19:44 UTC, thisiskaransgit commented
@Ghat0tkach, will you work on this one? Opening up a new PR and linking this one will do the work.

2023-06-09 19:47 UTC, Ghat0tkach commented
> @Ghat0tkach, will you work on this one? Opening up a new PR and linking this one will do the work.

Yup sure , Thank you!

2023-06-10 13:30 UTC, closed without merging