fix the failing lint tests
meshery/meshery-linkerd pull request #507
Opened 2023-05-10 10:54 UTC by ayushthe1

**Description**

This PR fixes #506 

**Notes for Reviewers**
Some tests are still failing. To fix those ,some changes would have to be done in the `meshery-adapter-library` .

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-05-11 03:54 UTC, Aisuko requested changes
Please check the CI result and update the code. Your work is so clear.

2023-05-11 03:54 UTC, Aisuko commented on linkerd/linkerd.go
> +		comp, parseErr := oam.ParseApplicationComponent(acomp)
Meshery stop support OAM already. We can ignore OAM-related functions.

2023-05-13 02:02 UTC, Aisuko commented
Hi @ayushthe1 Thanks for your contribution, there are still some errors from the CI. Could you solve all of them? Maybe some mistakes should be ignored.

2023-05-17 14:12 UTC, ayushthe1 commented
@Aisuko Could you specify which lint tests should i ignore ?Also could you please review the changes i have done to the `init` functions .I have some doubt on them.

2023-05-18 00:58 UTC, Aisuko commented
> @Aisuko Could you specify which lint tests should i ignore ?Also could you please review the changes i have done to the `init` functions .I have some doubt on them.

Hi @ayushthe1, 

Here is result from `golangci-lint`, if you can help to fix this, it would be good, but I know it is not easy to solve. So, if it can cause any breaking change, please ignore them in this PR,

For Golang code.

```
run golangci-lint
  Running [/home/runner/golangci-lint-1.52.2-linux-amd64/golangci-lint run --out-format=github-actions --timeout 3m --verbose] in [] ...
  Error: hugeParam: opReq is heavy (112 bytes); consider passing it by pointer (gocritic)
  Error: hugeParam: oamReq is heavy (88 bytes); consider passing it by pointer (gocritic)
  Error: should rewrite http.NewRequestWithContext or add (*Request).WithContext (noctx)
  Error: should rewrite http.NewRequestWithContext or add (*Request).WithContext (noctx)
  Error: named return "t1" with type "time.Time" found (nonamedreturns)
  Error: named return "loc" with type "string" found (nonamedreturns)
```

For E2E Tests part, we can ignore this part currently. We are working to make sure the E2E test can be useful in the future.

2023-05-18 01:10 UTC, Aisuko requested changes

2023-05-18 01:10 UTC, Aisuko commented on internal/config/releases.go
> +	req, err := http.NewRequest("GET", releaseAPIURL, http.NoBody)
Is there I have considered the suggestion from `golangci-lint`?

`should rewrite http.NewRequestWithContext or add (*Request).WithContext (noctx)`

2023-05-18 01:10 UTC, Aisuko commented on linkerd/cert/cert.go
> +func GetWindow(t time.Time, lifetime, clockSkewAllowance time.Duration) (t1, t2 time.Time) {
Please check the CI feedback here.  `named return "t1" with type "time.Time" found (nonamedreturns)`

2023-05-18 01:10 UTC, Aisuko commented on linkerd/install.go
> +func getChartLocationAndVersion(version string) (loc, ver string) {
Same here.

2023-05-18 01:10 UTC, Aisuko commented on linkerd/install.go
> +	req, err := http.NewRequest("GET", url, http.NoBody)
Same here.

2023-05-19 06:07 UTC, ayushthe1 commented
Thanks for reviewing @Aisuko .I have solved all the error except one. There is a test called `nonamedresults` which i have disabled because this and one another test (gocritic) gives conflicting suggestions .Like if you solve the `nonamedresults`, then the other error will pop out and vice-versa. 
The one error that is still left to be resolved will require changes in the `Adapter` struct inside the `meshery-adapter-library`. Should i go forward with making those changes ? Also can you please take a look at changes i have done to the `init()` function in this PR where i have replaced them.

2023-07-13 20:58 UTC, closed without merging